In [25]:
## Test Connection to DB 

from sqlalchemy import create_engine
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

engine = create_engine('postgresql+psycopg2://postgres:password123@localhost:5432/nba_pipeline')

df_test = pd.read_sql("SELECT * FROM standings LIMIT 5", engine)
df_test

,team,wins,losses,win_loss_pct,games_back,pts_per_game,opp_ppg,srs,conference,team_abbrev
0,Detroit Pistons,60,22,0.732,0.0,117.8,109.6,7.53,East,DET
1,Boston Celtics,56,26,0.683,4.0,114.9,107.2,7.37,East,BOS
2,New York Knicks,53,29,0.646,7.0,116.5,110.1,6.05,East,NYK
3,Cleveland Cavaliers,52,30,0.634,8.0,119.5,115.4,3.78,East,CLE
4,Toronto Raptors,46,36,0.561,14.0,114.6,111.8,2.75,East,TOR

In [4]:
## query for top 10 scoeres

query =   """
SELECT player, team, ROUND(pts::numeric/games,1) as ppg
FROM player_stats
WHERE games > 40
ORDER BY ppg DESC
LIMIT 10 
"""

df_top_scorers = pd.read_sql(query, engine)
df_top_scorers

                    player team   ppg
0              Luka Dončić  LAL  33.5
1  Shai Gilgeous-Alexander  OKC  31.1
2          Anthony Edwards  MIN  28.8
3             Jaylen Brown  BOS  28.7
4             Tyrese Maxey  PHI  28.3
5         Donovan Mitchell  CLE  27.9
6            Kawhi Leonard  LAC  27.9
7             Nikola Jokić  DEN  27.7
8          Lauri Markkanen  UTA  26.7
9            Stephen Curry  GSW  26.6

In [13]:
## graph 

fig = px.bar(df_top_scorers, x = 'player', y='ppg', title = 'Top 10 NBA scorers 2025-26', 
labels = {'ppg' :'Points Per Game', 'player' : 'Player'}, color = 'team')
fig.show()

In [6]:
## Query team wins vs team pts_per_game scatter plot

query ="""
SELECT team, wins, pts_per_game, opp_ppg, conference
FROM standings
ORDER BY wins DESC
"""

df_standings_viz = pd.read_sql(query, engine)
df_standings_viz

                      team  wins  pts_per_game  opp_ppg conference
0    Oklahoma City Thunder    64         119.0    107.9       West
1        San Antonio Spurs    62         119.8    111.5       West
2          Detroit Pistons    60         117.8    109.6       East
3           Boston Celtics    56         114.9    107.2       East
4           Denver Nuggets    54         122.1    116.9       West
5          New York Knicks    53         116.5    110.1       East
6       Los Angeles Lakers    53         116.3    114.6       West
7      Cleveland Cavaliers    52         119.5    115.4       East
8          Houston Rockets    52         115.2    110.0       West
9   Minnesota Timberwolves    49         118.0    114.6       West
10         Toronto Raptors    46         114.6    111.8       East
11           Atlanta Hawks    46         118.5    116.0       East
12            Phoenix Suns    45         112.6    111.1       West
13      Philadelphia 76ers    45         115.9    116.1       East
14           Orlando Magic    45         115.7    115.1       East
15       Charlotte Hornets    44         116.0    111.2       East
16              Miami Heat    43         120.9    118.5       East
17  Portland Trail Blazers    42         115.5    115.8       West
18    Los Angeles Clippers    42         113.8    112.6       West
19   Golden State Warriors    37         114.6    115.2       West
20         Milwaukee Bucks    32         110.6    116.8       East
21           Chicago Bulls    31         116.3    121.5       East
22    New Orleans Pelicans    26         115.5    120.0       West
23        Dallas Mavericks    26         114.1    119.6       West
24       Memphis Grizzlies    25         114.7    120.7       West
25        Sacramento Kings    22         111.0    121.0       West
26               Utah Jazz    22         117.6    126.0       West
27           Brooklyn Nets    20         105.9    115.9       East
28          Indiana Pacers    19         112.4    120.4       East
29      Washington Wizards    17         112.9    124.9       East

In [18]:
fig = px.scatter(df_standings_viz, x = 'pts_per_game', y ='wins',
labels =  {'wins' :'Wins', 'pts_per_game' : 'Points Per Game', 'team' :"Team"}, color = 'conference', hover_data=['team', 'opp_ppg'], trendline='ols')
fig.show()

In [36]:
## % of points from top 3 scorers — bar chart by team

query = """
SELECT top_3.team, stand.wins, top_3.pts_top_3, team_total.total_pts, 
ROUND(top_3.pts_top_3/team_total.total_pts::numeric, 3) as pct_top_3 FROM
(SELECT team, ROUND(SUM(pts)::numeric,0) as pts_top_3 FROM
(SELECT player, team, pts, games,
RANK() OVER (PARTITION BY team ORDER BY pts DESC) as rank_total_pts
FROM player_stats as ps) as sub
WHERE rank_total_pts <= 3
GROUP BY team) top_3 
JOIN
(SELECT team, ROUND(SUM(pts)::numeric, 0) as total_pts
FROM player_stats
GROUP BY team) team_total ON top_3.team = team_total.team
JOIN
(SELECT wins, team_abbrev
FROM Standings) stand ON team_total.team = stand.team_abbrev
ORDER BY pct_top_3 DESC
"""
df_top3_score_pct = pd.read_sql(query, engine)


#fig = px.bar(df_top3_score_pct, x='team', y='wins', labels = {'team': 'Team','wins': 'Wins', 'pct_top_3': 'Top 3 scorers %'})
#fig.show()

fig = go.Figure(
    data=go.Bar(x=df_top3_score_pct['team'], y=df_top3_score_pct['wins'], name = 'Teams wins')
)
fig.add_trace(go.Scatter(
              x=df_top3_score_pct['team'], y=df_top3_score_pct['pct_top_3'],yaxis ='y2', name="Top 3 scorers %")
)

fig.update_layout(
    title = 'Team Wins with Top 3 Scorers %',
    yaxis2=dict(
        overlaying='y',
        side='right'
    )
)
fig.show()