In [ ]:
#test Connect to SQL DB

from sqlalchemy import create_engine
import pandas as pd

engine = create_engine('postgresql+psycopg2://postgres:password123@localhost/nba_pipeline')

In [2]:
df_test = pd.read_sql("SELECT * FROM standings LIMIT 5", engine)
df_test

,team,wins,losses,win_loss_pct,games_back,pts_per_game,pts_allowed_per_game,srs,conference,team_abbrev
0,Detroit Pistons,60,22,0.732,0.0,117.8,109.6,7.53,East,DET
1,Boston Celtics,56,26,0.683,4.0,114.9,107.2,7.37,East,BOS
2,New York Knicks,53,29,0.646,7.0,116.5,110.1,6.05,East,NYK
3,Cleveland Cavaliers,52,30,0.634,8.0,119.5,115.4,3.78,East,CLE
4,Toronto Raptors,46,36,0.561,14.0,114.6,111.8,2.75,East,TOR

In [3]:
## import librarites and engine connect

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine('postgresql+psycopg2://postgres:password123@localhost/nba_pipeline')

Matplotlib is building the font cache; this may take a moment.

In [4]:
## query for top 10 scoeres

query =   """
SELECT player, team, ROUND(pts::numeric/games,1) as ppg
FROM player_stats
WHERE games > 40
ORDER BY ppg DESC
LIMIT 10 
"""

df_top_scorers = pd.read_sql(query, engine)
df_top_scorers

                    player team   ppg
0              Luka Dončić  LAL  33.5
1  Shai Gilgeous-Alexander  OKC  31.1
2          Anthony Edwards  MIN  28.8
3             Jaylen Brown  BOS  28.7
4             Tyrese Maxey  PHI  28.3
5         Donovan Mitchell  CLE  27.9
6            Kawhi Leonard  LAC  27.9
7             Nikola Jokić  DEN  27.7
8          Lauri Markkanen  UTA  26.7
9            Stephen Curry  GSW  26.6

In [10]:
## graph 

fig = px.bar(df_top_scorers, x = 'player', y='ppg')
fig.show()